---
name: "Setup Go with Runner Hardening"
description: "Reusable action to set up Go"
inputs:
  token:
    description: "GitHub token for checkout (optional)"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
      with:
        go-version-file: ".go-version"
        cache: true
