---
# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json
version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - bodyclose
    - gocritic
    - gosec
    - misspell
    - rowserrcheck
    - unconvert
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
        text: "G703"
