---
doublestar: true
gitignore_excludes: true
formatter:
  type: basic
  include_document_start: true
  retain_line_breaks_single: true
  scan_folded_as_literal: false
  max_line_length: 0
  trim_trailing_whitespace: true
  array_indent: 2
  force_array_style: block
include:
  - ./**/*.yml
  - ./**/*.yaml
  - .github/**/*.yml
  - .github/**/*.yaml
# exclude:
