---
# gibidify configuration example
# Place this file in one of these locations:
# - $XDG_CONFIG_HOME/gibidify/config.yaml
# - $HOME/.config/gibidify/config.yaml
# - Current directory (if no gibidify.yaml output file exists)

# File size limit in bytes (default: 5MB)
fileSizeLimit: 5242880

# Directories to ignore during scanning
ignoreDirectories:
  - vendor
  - node_modules
  - .git
  - dist
  - build
  - target
  - bower_components
  - cache
  - tmp
  - .next
  - .nuxt

# FileType registry configuration
fileTypes:
  # Enable/disable file type detection entirely (default: true)
  enabled: true

  # Add custom image extensions
  customImageExtensions:
    - .webp
    - .avif
    - .heic
    - .jxl

  # Add custom binary extensions
  customBinaryExtensions:
    - .custom
    - .proprietary
    - .blob

  # Add custom language mappings
  customLanguages:
    .zig: zig
    .odin: odin
    .v: vlang
    .grain: grain
    .gleam: gleam
    .roc: roc
    .janet: janet
    .fennel: fennel
    .wast: wast
    .wat: wat

  # Disable specific default image extensions
  disabledImageExtensions:
    - .bmp  # Disable bitmap support
    - .tif  # Disable TIFF support

  # Disable specific default binary extensions
  disabledBinaryExtensions:
    - .exe  # Don't treat executables as binary
    - .dll  # Don't treat DLL files as binary

  # Disable specific default language extensions
  disabledLanguageExtensions:
    - .bat  # Don't detect batch files
    - .cmd  # Don't detect command files

# Maximum concurrency (optional)
maxConcurrency: 16

# Supported output formats (optional validation)
supportedFormats:
  - json
  - yaml
  - markdown

# File patterns for filtering (optional)
filePatterns:
  - "*.go"
  - "*.py"
  - "*.js"
  - "*.ts"

# Output and template customization
output:
  # Template selection: default, minimal, detailed, compact, or custom
  template: "default"
  # Metadata options
  metadata:
    includeStats: true
    includeTimestamp: true
    includeFileCount: true
    includeSourcePath: true
    includeFileTypes: false
    includeProcessingTime: false
    includeTotalSize: false
    includeMetrics: false
  # Markdown-specific options
  markdown:
    useCodeBlocks: true
    includeLanguage: true
    headerLevel: 2
    tableOfContents: false
    useCollapsible: false
    syntaxHighlighting: true
    lineNumbers: false
    foldLongFiles: false
    maxLineLength: 120
    customCSS: ""
  # Custom template overrides (when template is "custom")
  custom:
    header: ""
    footer: ""
    fileHeader: ""
    fileFooter: ""
  # Custom template variables
  variables:
    project_name: "My Project"
    author: "Developer Name"
    version: "1.0.0"
