---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: PR Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

permissions: {}

jobs:
  Linter:
    name: PR Lint
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Go
        uses: ./.github/actions/setup
        with:
          token: ${{ github.token }}

      - uses: ivuorinen/actions/pr-lint@877acc6d8b013051a6acf83c0e876d3a2b46210a # v2026.06.08
