---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Go Tests with Coverage to SARIF

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Get dependencies
        shell: bash
        run: go mod tidy

      - name: Run tests with coverage
        shell: bash
        run: |
          go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - name: Install go-coverage-to-sarif
        shell: bash
        run: go install github.com/michaelestrin/go-coverage-to-sarif@latest

      - name: Convert Go coverage to SARIF
        shell: bash
        run: go-coverage-to-sarif coverage.out coverage.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: coverage.sarif
